### PR TITLE
Create sketch.js

### PR DESCRIPTION
**Pull request by Meir1Bookatz**
function setup() {
	// createCanvas(550, 550);
	createCanvas(windowWidth, windowHeight);
	background(125);
}

function draw() {
	followCursor.init();
  followCursor.run();
}

var followCursor = (function() {
  var s = window.document.createElement('div');
	s.style.position = 'absolute';
	s.style.left = '50%';
	s.style.top = '50%';
	s.style.width = '0';
	s.style.height = '0';
	s.style.borderLeft = '5px solid transparent';
	s.style.borderRight = '5px solid transparent';
	s.style.borderBottom = '15px solid white';
	var rotation = 0;
	var y =s.getBoundingClientRect().top;
	var x =s.getBoundingClientRect().left;
	 window.addEventListener('keydown', function (e) {
		switch (e.key) {
			case 'ArrowUp':
			s.style.top = (s.getBoundingClientRect().top - 2)+ 'px';
			break;
			case 'ArrowDown':
			s.style.top = (s.getBoundingClientRect().top + 2)+ 'px';
			break;
			case 'ArrowLeft':
			s.style.left = (s.getBoundingClientRect().left - 2)+ 'px';
			// rotation-=3;
			break;
			case 'ArrowRight':
			s.style.left = (s.getBoundingClientRect().left + 2)+ 'px';
			// rotation+=3;
		}
		if (rotation>=360) {
			rotation-=360;
		} else if (rotation<0) {
			rotation+=360;
		}
	});

  return {
    init: function() {
      document.body.appendChild(s);
    },

    run: function() {
      var e = e || window.event;
      // s.style.left  = (e.clientX - 10) + 'px';
      // s.style.top = (e.clientY - 10) + 'px';
			// s.style.top = s.getBoundingClientRect().top + 'px';
			// s.style.left = s.getBoundingClientRect().left + 'px';
			s.style.transform = 'rotate('+rotation+'deg)';
			document.getElementById('ship').innerHTML = rotation+' degs' + '<br> X: ' + s.getBoundingClientRect().top+ '<br> Y: ' + s.getBoundingClientRect().left;
    }
  };
}());

// window.onload = function() {
//   followCursor.init();
//   followCursor.run();
// }

### CODE REVIEW

**Comment by Meir1Bookatz** [comment]
i have a new idea, what if the user can move in all 4 directions with the arrow keys but the ship always faces the mouse and then either space bar or mouse click can make it shoot.

**Comment by jared-swanzen** [comment]
It's gonna be a lot harder to "unclunk" it, but I'm all for it😂

**Comment by Meir1Bookatz** [comment]
can you work on the ship moving with the arrow keys and ill do the mouse? or the other way around idm.

**Comment by Meir1Bookatz** [comment]
never mind i did it lol

**Comment by Meir1Bookatz** [comment]
the only thing with it is that only one key works at a time.

**Comment by jared-swanzen** [comment]
You just need to change the KeyPressed to OnKeyDown or something like that

**Comment by Meir1Bookatz** [comment]
yeah i tried the problem is that the switch statement can only accept one argument at a time.

**Comment by Meir1Bookatz** [comment]
heres a great page ive been trying to figure out, see if its any help https://stackoverflow.com/questions/40120470/javascript-making-image-rotate-to-always-look-at-mouse-cursor

**Comment by jared-swanzen** [comment]
I love what they're doing there 😱
I have to look at that in more detail tho. I'll do that after tomorrow, I
kinda have to study fir a Computer Science test tomorrow

**Pull request merged**
